version: '3.3'

services:
  db:
    container_name: labum-fatec
    image: postgres
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - ./dbconfig:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - POSTGRES_DB=labum
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
volumes:
  pg_data: